# Generated by Django 4.0.3 on 2022-03-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('dsg', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, default='Ghaziabad', max_length=20)),
                ('state', models.CharField(blank=True, default='Trainer', max_length=20)),
            ],
        ),
    ]
