# Generated by Django 4.0.3 on 2022-03-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='name',
        ),
    ]
